FROM python:3.8.18

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

ADD ./chatbot/actions /app/actions

WORKDIR /app/actions

RUN pip install rasa

CMD /wait && rasa run actions